version: 2.1

jobs:
  run_bot_tor:
    docker:
      - image: cimg/python:3.10-browsers
    steps:
      - checkout
      - run:
          name: Install Tor and Privoxy
          command: |
            sudo apt-get update
            sudo apt-get install -y tor privoxy
            # Konfigurasi Privoxy agar nyambung ke Tor
            echo "forward-socks5t / 127.0.0.1:9050 ." | sudo tee -a /etc/privoxy/config
      - run:
          name: Install Dependencies
          command: pip install selenium
      - run:
          name: Run Script
          command: |
            chmod +x start.sh
            ./start.sh
      - run-bot
